version: 0.0
os: linux

# Copy all files from CodeCommit to the app directory
files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user    

hooks:
  ApplicationStop:
    - location: /home/ec2-user/app/scripts/app_stop.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: /home/ec2-user/app/scripts/app_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: /home/ec2-user/app/scripts/app_start.sh
      timeout: 300
      runas: ec2-user
